// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBARIJhN1RETYauv4RcngQubDLGhUmtnps',
    appId: '1:58511212362:web:1c29d16b7bafcf11994bb3',
    messagingSenderId: '58511212362',
    projectId: 'itigroup3-78e0f',
    authDomain: 'itigroup3-78e0f.firebaseapp.com',
    storageBucket: 'itigroup3-78e0f.appspot.com',
    measurementId: 'G-JGD7QW1J0R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdIw8gBTHIzt1lWFp2Ggz2uvEuVtR1Lh0',
    appId: '1:58511212362:android:a5ebd1ad72e34365994bb3',
    messagingSenderId: '58511212362',
    projectId: 'itigroup3-78e0f',
    storageBucket: 'itigroup3-78e0f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsrKlZ2J2hQedflvLXuPKzYbzIKTzyIyU',
    appId: '1:58511212362:ios:770295ef14da707a994bb3',
    messagingSenderId: '58511212362',
    projectId: 'itigroup3-78e0f',
    storageBucket: 'itigroup3-78e0f.appspot.com',
    iosClientId: '58511212362-5ifkpcanephjnaa9iiq3a6320vif24h2.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginDesign',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsrKlZ2J2hQedflvLXuPKzYbzIKTzyIyU',
    appId: '1:58511212362:ios:b4a634d284c919fc994bb3',
    messagingSenderId: '58511212362',
    projectId: 'itigroup3-78e0f',
    storageBucket: 'itigroup3-78e0f.appspot.com',
    iosClientId: '58511212362-scovqgm63q5ihcdk6kefgmedjegvtts3.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginDesign.RunnerTests',
  );
}
